### ISSUE TITLE
Boussoles customs

### ISSUE THREAD

**Issue by Spirit-10** [zelytra/Daedalus#12]
**1) "Boussole divine"** (nom temporaire)
Pointe vers un temple présent dans la partie au choix, via shift + clic droit (c'était bien ça Zelytra ?).

Si le Dieu est invoqué, pointe vers le Dieu et non le temple.

Ne pointe PAS le Minotaure.

Craft custom à déterminer. 

**2) "Boussole humaine"** (nom temporaire aussi)
Pointe vers le camp de base de chaque équipe en donnant à chaque intersection la direction à prendre pour retourner au spawn de l'équipe.

Disponible d'entrée de jeu.

**Comment by dadodasyra** [comment]
Je pense que la bousolle humaine devrait plus être en ui, soit en popup ou tip (au dessus de hotbar) soit en scoreboard. C'est une perte de place dans la hotbar

**Comment by Spirit-10** [comment]
En fait Nico a déjà codé quelque chose donnant le pathfinding, faut voir si tu peux l'appliquer en popup comme tu dis ou si ça marche que pour une boussole. 
Merci pour l'idée !

**Comment by dadodasyra** [comment]
Oui oui le pathfinding on en avait discuté, forcément, mais juste je veux dire l'intégré à une flèche en ui au lieu de prendre un slot pour ça
