### ISSUE TITLE
Hades

### ISSUE THREAD

**Issue by zelytra** [zelytra/Daedalus#156]
Ajouter plus de vie au wither skeleton

**Comment by Spirit-10** [comment]
Donner du stuff au joueur revive, par exemple full D P2 avec sharpness 3, 20 steaks et 5 GAP ? (à équilibrer)

**Comment by Spirit-10** [comment]
DECISION FINALE : 
- Actif modifié : effet de Wither II 5 s (rayon = 8 blocs) activable toutes les 30 secondes, avec effet de blindness visuel ;
- Stuff donné : plastron/bottes en diamant, casque/jambières en fer full P2, épée en diamant sharpness 2, 20 steaks, pioche en fer Efficency 2, bouclier, arc non enchanté et 16 flèches
