### ISSUE TITLE
Nerf Ares

### ISSUE THREAD

**Issue by zelytra** [zelytra/Daedalus#159]
Retirer l'effet strenght continue du dieu

**Comment by zelytra** [comment]
Donner du stuff au joueur revive pour ne pas se faire insta kill

**Comment by Spirit-10** [comment]
Ou sinon on peut virer le Strenght constant et faire en sorte d'appliquer le pouvoir de la bannière aussi au Dieu. 

Attention c'est pour Hadès ton deuxième message, je créé une issue.

**Comment by Spirit-10** [comment]
DECSION FINALE UNIQUE : on vire juste l'effet de snowball collectif après un kill.
