### ISSUE TITLE
Craft custom boussole

### ISSUE THREAD

**Issue by Spirit-10** [zelytra/Daedalus#36]
Emeraude x2 | Obsidienne | Emeraude x2
Emeraude x2 | Deux blocs de fer | Emeraude x2
Silex | Redstone x4 | Silex

**Comment by dadodasyra** [comment]
Un craft avec un nombre d'item precis en input sur un slot c'est chiant. Et les emeraudes faudrait rajouter de la difficulté, y'en a trop.

**Comment by dadodasyra** [comment]
Et le silex je vois pas le rapport

**Comment by Spirit-10** [comment]
"Il dit qu'il voit pas le rapport"

Le nombre d'item précis c'est ça pour tous les crafts en fait.
Ouais on peut monter le nombre d'émeraudes, mais après c'est un item early game qui doit pas être trop chiant à avoir. 
Silex : facile d'avoir, en forme de triangle genre pointe vers un endroit, d'où mon choix.
