### ISSUE TITLE
Gamerules à éditer

### ISSUE THREAD

**Issue by Spirit-10** [zelytra/Daedalus#39]
Mettre le mob loot en true et le daylight cycle en true par défaut

**Comment by zelytra** [comment]
C'est déja le cas
`Bukkit.getWorld("world").setGameRule(GameRule.DO_TILE_DROPS,true);
Bukkit.getWorld("world").setGameRule(GameRule.DO_ENTITY_DROPS,true);
Bukkit.getWorld("world").setGameRule(GameRule.KEEP_INVENTORY, false);`
