### ISSUE TITLE
Divine tracker

### ISSUE THREAD

**Issue by Spirit-10** [zelytra/Daedalus#41]
Le divine tracker doit repop lors du respawn du joueur.

**Comment by zelytra** [comment]
C'est déja le cas
`Bukkit.getWorld("world").setGameRule(GameRule.DO_TILE_DROPS, true);Bukkit.getWorld("world").setGameRule(GameRule.DO_ENTITY_DROPS, true);Bukkit.getWorld("world").setGameRule(GameRule.KEEP_INVENTORY, false);`
