### ISSUE TITLE
MythicMobs

### ISSUE THREAD

**Issue by uiytt** [zelytra/Daedalus#5]
Première chose, félicitation pour votre projet. Ça fait tellement plaisir de voir des projets de mini jeux autre que UHC apparaître et le vôtre semble vraiment prometteur. Merci de le partager :+1:  et encore une fois bravo.

Vous avez mentionné des mobs customs pour les donjons et ça serait sympa si il était possible d'ajouter quelques mobs plus intéressants à combattre comme le propose mythicMobs.

Cela n'est pas simple car il faut en plus ajouter un certain système de customisation sur les donjons mais je pense que ça pourrait être très intéressant. De toute manière je doute que vous l'intégreriez dans la V1.

En tout cas bravo pour votre projet, je l'attend avec impatience.

**Comment by zelytra** [comment]
Hello,
Merci pour le soutient ! Ca fait plaisir de voir ce style commentaire !

A propos des mobs customs, nous comptons ajouter des mobs customs à chaque temple. Mais nous n'utiliserons pas ce plugin. Nous limitons au maximum les dépendances et donc si jamais on as besoin de faire quelque chose "comme" MythicMobs nous le coderons nous même. 
Dans la génération des temples cette partie est déjà codé et en attente de choix des mobs à implémenter donc aucun soucis de ce point de vue.

**Comment by uiytt** [comment]
Je comprends x) 
Bonne chance du coup, j'attends votre mini-jeux avec impatience
