### ISSUE TITLE
Ressentis des malédictions

### ISSUE THREAD

**Issue by uiytt** [zelytra/Daedalus#6]
Juste pour être claire, je veux pas paraître chiant et je comprends que c'est avant tout votre propre projet et donc c'est votre décision (surtout que vous connaissez le mini jeux depuis bien plus longtemps).

J'ai lu votre wiki et le jeu semble vraiment incroyable mais j'ai l'impression en tant que joueur (même si je n'ai jamais joué dessus) que les malédictions sont plus chiantes qu'autres choses et n'apportent pas grand chose. Certaines comme Méduse et Tantale semble vraiment pire, le fait de ne presque pas pouvoir courir pendant 20 minutes ou d'être constamment figé semble plus être un moyen de vraiment passer un mauvais épisode au lieu de s'amuser. 

Voici mon petit avis pour avoir participé à pas mal de petit mini jeux.

Bonne chance et merci pour le mini-jeux :)

**Comment by zelytra** [comment]
Hello,
Pas de soucis au contraire on est ouvert aux avis extérieur au vue qu'on est en tète baissé dedans donc le point de vue d'un œil neuf ne fait pas de mal !

Alors, les malédictions portent bien leurs nom car leurs but est d'handicapé une équipe. Ce sujet est encore en discussion donc sera très probablement modifié avant la beta. Actuellement la tète de Médusa à été développé et ne vas pas complétement ruiné l'épisode d'une équipe. Au contraire, après nos tests, et de la manière dont on l'a réalisé, on trouve cette malédiction marrante et si bien utilisé peut être très utiles en pvp. Les joueurs ne vont pas être constamment freeze mais uniquement quand il regarderons le corp d'une personne possédant la tète. Donc tu t'en feras un avis pendant la beta !

Aucune malédiction a pars Médusa n'as été faite donc le wiki sera mis a jour une fois qu'on s'en chargera.

**Comment by uiytt** [comment]
Je n'ai pas testé le Médusa donc je vous fait confiance. Mais je pense que ne pas pouvoir courir pendant 20 minutes peut être vraiment énervant.
J'ai aussi du mal à voir l’intérêt des malédictions, celles ci semblent apporter très peu de choses dans le jeu autre que de la frustration.
Après si vous arrivez à les rendre toutes sympa plus qu'énervantes comme vous l'avez fait avec Médusa alors tant mieux.

Dans tous les cas c'est une bêta et vous aurez rapidement des retours de joueurs qui vous indiqueront si c'est un problème.

**Comment by Spirit-10** [comment]
Yes c'est vrai que ça peut être galère pour les joueurs sans bonus derrière, mais d'un autre côté j'avais eu l'idée pour d'une part avoir un truc RP et d'autre part, surtout, pour que le Minotaure prenne pas trop cher pendant la partie. Car j'avais peur qu'il se fasse sauter assez violemment avec sa team, donc ça permettait de balancer vis-à-vis des joueurs. 
Après oui d'un point de vue joueur c'est chiant, mais ça dure que 20 minutes et tu ne peux être maudit qu'une fois. 
On verra ça in game mais ça peut être réduit à 10 minutes oui si c'est trop pété, on est ouvert aux modifications exigées par le gameplay ;)

**Comment by uiytt** [comment]
Oui c'est vrai que je me disais aussi que les minotaures vont prendre chère x) 
Surtout si les teams font une alliance. 

20 minutes ça reste long, mais bon on verra bien après les premières parties. 
Je ferme en attendant des tests et j'ouvrerai de nouveau si en jouant ça semble vraiment chiant.
