### ISSUE TITLE
Drop invisibles ou non récupérables

### ISSUE THREAD

**Issue by Spirit-10** [zelytra/Daedalus#63]
Quand les items des mines droppent, parfois ils sont invisibles, et parfois certains ne pouvaient pas être récupérés par des joueurs.

**Comment by dadodasyra** [comment]
Très probablement non réglable. Peut etre coté client ou spigot à blamer. Il faudrait se renseigner

**Comment by zelytra** [comment]
Impossible à reproduire, bug non avéré
