### ISSUE TITLE
Equilibrage Athéna

### ISSUE THREAD

**Issue by Spirit-10** [zelytra/Daedalus#75]
Rajouter comme pouvoir : une carte qui s'actualise toutes les 5 minutes avec une taille à préciser (50-100 blocs autour ?), qu'Athéna peut donner à un joueur de son équipe si elle veut. 

Attention : voir si on peut gérer l'affichage des joueurs non pas en temps réel (sauf l'équipe d'Athéna SI possible) mais tous les x temps (15 secondes ?).

**Comment by zelytra** [comment]
Possible
